

services:
  extraction:
    build: ./extraction
    volumes:
      - ./data:/data

  chunking_embedding:
    build: ./chunking_embedding
    volumes:
      - ./data:/data
    depends_on:
      - extraction

  clustering_summarization:
    build: ./clustering_summarization
    volumes:
      - ./data:/data
    depends_on:
      - chunking_embedding  

  milvus_integration:
    build: ./milvus_integration
    volumes:
      - ./data:/data
    depends_on:
      - clustering_summarization

  retrieval:
    build: ./retrieval
    volumes:
      - ./data:/data
    depends_on:
      - milvus_integration



